theme: minima
title: Apurv's Portfolio
author: Apurv Vidhate
description: Computer Science graduate from The University of Texas at Arlington, skilled in Python, Distributed systems, Databases, Artificial Intelligence, Machine Learning, and Software Engineering. 
Earned a Bachelor's in Computer Science and Engineering with first-class distinction from MIT ADT University. Demonstrated leadership by organizing various technical and non-technical events. Passionate about contributing to the computer science industry and making a positive impact.
